Repository Operation-Eclipse/red-eclipse-14, pull requests merged in 2023-08, with the labels that each got.

#14 Small fix for recipes in Assemblers
  Resources/Prototypes/_RedEclipse/Entities/Objects/Factory/Structures/Assemblers/FactoryAdvancedAssembler.yml
  Resources/Prototypes/_RedEclipse/Entities/Objects/Factory/Structures/Assemblers/FactoryExplosiveAssembler.yml
  Resources/Prototypes/_RedEclipse/Entities/Objects/Factory/Structures/Assemblers/FactoryWeaponBodyAssembler.yml
Labels: No C#

#18 Fixed machines that require vanilla basic materials
  Resources/Prototypes/_RedEclipse/Entities/Objects/Factory/Structures/Assemblers/BaseFactoryMachine.yml
Labels: No C#

#17 Syndetroit
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/syndetroit.yml
  Resources/Prototypes/Maps/syndetroit.yml
Labels: Changes: Map

#19 map recoloring and changes
  Resources/Maps/_RedEclipse/syndetroit.yml
Labels: No C#, Status: Needs Review
